# ./Dockerfile.nginx
FROM nginx:alpine

# Удаляем дефолтный конфиг nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем НАШ конфиг из папки nginx/ в контейнер
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранный фронтенд (папку frontend/dist) в папку nginx
COPY ./frontend/dist /usr/share/nginx/html